on:
  push:
    branches:
      - rc

permissions:
  contents: write
  pull-requests: write

name: release-rc

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          config-file: .github/release-please-config-rc.json
          manifest-file: .github/.release-please-manifest-rc.json
          target-branch: ${{ github.ref_name }}
